nylas/nylas-mail

- .travis.yml
- package.json
Adds travis-ci integration including setup, building and testing your specs. Though this is currently not succeeding on Node 4 this might be a good idea to run continuous integration tests on this fabulous peace of software.
> Add basic travis-ci integration

- .travis.yml
- build/Gruntfile.coffee
- src/flux/models/label.coffee
I noticed on the official N1 travis page it succeeded, but the actual spec tester failed run because it couldn't connect to a X11 display. I took the liberty of revamping the travis build script to follow Atom's example and build separately on Linux and OS X.
The Linux build is still having issues, but I do not know how they are occurring. I probably will setup a Ubuntu Precise box just to solve the issues. The OS X build completes spectacularly with the spec test being run, and all of them passing.
EDIT: The Travis script uses a developer Github API OAuth key. Just follow the instructions at https://developer.github.com/v3/oauth/ to get a access token. Or continue using the one I generated.
> Travis update

- internal_packages/onboarding/lib/account-types.coffee
eas_server_host field added to internal_packages/onboarding/account-types.coffee to allow for specifying the Exchange server if necessary.
> Added eas_server_host field

- internal_packages/composer/stylesheets/composer.less
> Fixed a pixel cut in floating-toolbar

- build/resources/linux/debian/control.in
* Package libgcrypt11 is no longer available in Debian or Ubuntu
* Allow installing the package with libgcrypt20 instead
I was not able to install the Official .deb without this modification.
But after repacking the .deb with this change included, I was able to install and run N1 with no problems.
Debian Package Search:
https://packages.debian.org/search?keywords=libgcrypt&searchon=names&suite=stable&section=all
Ubuntu Package Search:
http://packages.ubuntu.com/search?keywords=libgcrypt&searchon=names&suite=wily&section=all
> Update debian package libgcrypt dependency

- build/Gruntfile.coffee
- build/package.json
- package.json
`vm-compatibility-layer` was designed to support obsolete APIs in node v0.11.x of node v0.10.x. It is only used in the build Gruntfile and nowhere else in the project.
I ran the build without `vm-compatibility-layer` and it completed with no errors, thus demonstrating its nonessential.
Atom already removed `vm-compatibility-layer` a few versions ago.
> Remove vm-compatibility-layer

- src/flux/stores/message-body-processor.coffee
39a142ddcb80c7e1fce22dfe1e0e628272154523 fixed the prime issue of #436, but introduced another issue. Facebook emails have a `""` body initially. The return statement in the `process` method of `MessageBodyProcessor` causes the method to return early, ignoring my extension that would set the body at https://github.com/mbilker/email-pgp/blob/master/lib/message-loader/message-loader-extension.es6#L19. This PR removes the return statement, but leaves in the change in the hash key for caching messages.
> Do not return when original body is null

- .travis.yml
- build/Gruntfile.coffee
- build/tasks/spec-task.coffee
- internal_packages/composer/spec/composer-view-spec.cjsx
This PR adds support for running the N1 Spec Suite under Linux. I only used the `master` branch of nylas/N1 for the testing. I haven't tested the `spectron` branch that is actively developing. There were some minor modifications made to the spec files to make the tests pass. `Xvfb` is installed in Travis and started only on Linux (doesn't exist on OS X clients) to provide a X11 window so the spec test doesn't complain there is no `DISPLAY` defined or available.
The keybinds differ between Mac OS X, Linux, and Windows. I added a wrapper for `cmdctrl` into each spec where the `cmd` keyboard modified was used (currently only found in `internal_packages/composer/spec/composer-view-spec.cjsx`).
> Travis Linux Testing

- build/resources/linux/debian/postinst
Changes the condition for detecting the distro name so ElementaryOS (ubuntu based) goes as an Ubuntu and the package installs.
> Allows package to be installed in ElementaryOS

- src/browser/application.coffee
Fixing #481
As mentioned on this Electron's issue: https://github.com/atom/electron/pull/2777
The `activate-with-open-windows` event has been deprecated in favor of a global `activate` event with a `hasVisibleWindows` parameter.
This prevents N1 from crashing when closing the main window and opening via clicking the Dock icon.
> Removing deprecated 'activate-with-no-open-windows' event

- build/resources/linux/redhat/nylas.spec.in
- build/tasks/mkrpm-task.coffee
In #107, other people reported the icons were not copied to the correctly. This PR installs the icons to Fedora's standard icon location (/usr/{local/}share/icons/hicolor). This PR changes the icon location in `nylas.desktop` to point to the new location.
> RPM copy N1 icons into hicolor folder

- src/flux/stores/file-download-store.coffee
From #412:
In src/flux/stores/FileDownloadStore.coffee, I noticed in _cleanupDownload on line 233-236 that you trigger the store update callbacks after deleting the fulfilled event.
This prevents me from using the event to detect when an attachment download finished in my PGP plugin. The events completed events are not present in the Object so I cannot detect the change.
> fix(FileDownloadStore): delete download from @_downloads after @trigger

- src/components/editable-list.jsx
The issue stems that Mac OS X uses a case-insensitive filesystem by default, while most Linux filesystems are case-sensitive. The classNames package will require successfully on Mac OS X during Travis tests, but since the spec test suite isn't normally run under Linux this bug is more unlikely to appear.
This PR changes the module name to `classnames` instead of `classNames` to account for case-sensitive filesystems.
> Require `classNames` throws error under Linux

- build/tasks/task-helpers.coffee
This bug appeared during a Travis test run, and only appeared on the Linux hosts running the tests. The function appears to treat the `process.env` as a set of functions, not properties.
This commit correctly interprets them as properties.
The main N1 repository no longer runs unit tests on Linux hosts, which is why this hasn't appeared during Travis builds, while my fork runs the unit tests on Linux under the Travis Ubuntu Trusty beta.
> Replace function accessor with property accessor in Grunt's task-helper script

- build/resources/linux/nylas.desktop.in
- build/tasks/install-task.coffee
EDIT: I forgot to mention this is with Linux and GNOME specifically.
Issue #465 mentions a missing icon.  This should fix that by using the application name for StartupWMClass in the resulting .desktop file.  I had this problem and this fixed it.
Issue #242 mentions a bad path for the icon in the .desktop file.  It was caused by having an extra parameter which then made the Icon invalid.  I had this same issue and this fixed it.
> Fix broken icon from issue #465 and Fix icon path for install

- spec/models/contact-spec.coffee
- src/flux/models/contact.coffee
This resolves #713. 
Tests have been added for this case but this change would parse a contact with the name "ev@nylas.com" to have a firstName of "Ev@nylas.com"
Previously this would have parsed to a firstName of "Ev". 
The only way around this is to introduce a email format check against names. I'm not sure how common it is to have a name field be a valid email address - but it might be more common than normal names that contain `@`.
> Names with @ are included in the contact name.

- appveyor.yml
This PR wraps the statements requiring access to the secure variables in an `if` statement to check if the variables are set. This successfully builds N1, **but** I have no feasible way to check if N1 works under Windows. The build currently _fails_ with the `AWS_ACCESS_KEY_ID` environment variable not found for publishing the finished build to AWS S3.
The only computer I have Windows on is my old Lenovo X300 from 2008, which I really don't want to dust off and power it up.
> AppVeyor Use no secure variables in Pull Requests

- CONTRIBUTING.md
In response to #879, this change replaces the reference to the invitation system to the Sync Engine to notify users that contributions to N1 do not require an invitation. The build instructions only reference the email credentials are required.
I need feedback on how the first paragraph under `Contributing to N1` should be phrased.
> Remove invitation references from `CONTRIBUTING.md`

- static/jasmine.less
Test error messages are unselectable by default. This PR adds the ability to select and copy error messages produced by the test suite.
> Make test output selectable

- script/bootstrap
The `script/bootstrap` command appears to log the module installation by default. This PR hides the output by default using the `--no-quiet` option check.
> Remove log of integration test package installation by default

- build/tasks/install-task.coffee
The `install` task would fail since `linuxShareDir` was undefined for the template `.desktop` file. This is caused by the passing `--install-dir` to `script/grunt install` pointing at a path not in `/tmp` or `TMPDIR`, and this action results in a separate code path the is not normally covered under the Travis CI suite.
> Grunt `install` task: Replace `shareDir` with `linuxShareDir` to reflect global changes

- internal_packages/thread-list/lib/thread-list-quick-actions.cjsx
- internal_packages/thread-list/lib/thread-list.cjsx
- internal_packages/thread-list/stylesheets/thread-list.less
It is difficult to extend the quick action list, since the current quick actions are inserted at once inside of the ThreadListQuickActions class. I've moved these into an injectable component set, which makes it possible to inject new quick actions that can be re-ordered to the front via a flexbox.
Here's an example:
> Move quick actions inside of flexbox with injectable component set

- script/mkdeb
Debian searches the `hicolor` directory by default and the [`postinst`](https://github.com/nylas/N1/blob/master/build/resources/linux/debian/postinst#L23) script rebuilds the cache at install time. This addition will add the icons of each size to the `hicolor` directory.
> Copy app icons to `hicolor` on Debian

- internal_packages/thread-list/lib/thread-list-quick-actions.cjsx
Because of changes made in #892, the archive and trash quick action buttons were inserted in the wrong order as can be seen below:
This fixes that issue so that they are in the same order as in the toolbar.
Sorry about this -- it was my fault for not checking before I submitted the previous pull request.
> Reorder archive and trash icons 

- internal_packages/phishing-detection/package.json
This was posted by `pkortge` on the Slack chat.
The `package.json` file reported the package name as `phishing`, which is incorrect as the folder is named `phishing-detection`. This PR sets the `name` value in `package.json` to `phishing-detection` so N1 loads the package.
> Set Phishing Detection package name to the correct value

- N1.sh
This prevents Electron saying it cannot find the main entrypoint, when using the `--test -s` parameters on the command line to spec test plugins.
I use this option when spec testing `email-pgp`, my PGP plugin, and want to use the N1 master repository instead of the installed N1.
> Allow additional parameters specified on command line

- internal_packages/message-list/lib/message-timestamp.cjsx
- internal_packages/message-list/spec/message-timestamp-spec.cjsx
The time format for closed vs. expanded in the message-list is not consistent.
Closed:
Expanded:
A number of other things change, but if the time format is the same, it'll appear as though the only thing changing with the time is adding the date before it.
This patch fixes that.
I have no opinion on lowercase vs. uppercase. Switching it to lowercase was just an easier change.
> Standardize capitalization to am/pm, for message-list

- src/flux/nylas-api.coffee
In the Slack chat, `niels` and `thomas` requested this feature to use their own Sync Engines hosted on their local networks. This PR allows a custom defined Sync Engine API Root and App ID.
While the config path can change to be more isolated in its own context, I believe the one I provided is suitable.
> Allow custom Sync Engine specified in `config.cson`

- src/nylas-spellchecker.coffee
The logic uses `if not` for CoffeeScript, but this checks if the constant `"en_US"` is not null, which is not the intended function of the check.
This PR fixes the intended functionality of the function and moves the `not` call to `in`.
> Fix logic for en_US default dictionary on Linux

- build/package.json
This addresses #1176. `csslint` removed the `package.json` `os` property in `0.10.0`. `grunt-contrib-csslint` updated to `csslint` in `0.2.0`. Atom uses `0.2.0`, but N1 can be better and use a newer version of the module.
> Bump grunt-contrib-csslint to to ~0.5.0

- src/window-event-handler.coffee
This code triggers when a window is supposed to close, but this error causes the DevTools to open and the window not exiting with the keyboard shortcut.
Please tell me if you want the `remote` module variable assignment within the `_.defer` block.
> Define the remote variable

- internal_packages/composer-spellcheck/lib/spellcheck-composer-extension.es6
- internal_packages/message-autoload-images/spec/autoload-images-extension-spec.es6
There are warnings in `spellcheck-composer-extension.es6` for the `while (true)` loops.
I do not know a better way off the top of my head, but these fixes will allow the Travis builds to complete and not fail. I am surprised my Travis builds from my personal fork still succeed.
> Correct eslint errors from Travis

- CONTRIBUTING.md
Updating Contributing guidelines to make note of the `env: custom` option so that a Sync Engine in a local environment may be accessed on an alternate IP.
Also APIRoot must contain quotes around the URL otherwise a config validation will be thrown.
Signed-off-by: Julien Chinapen <j.c@shogun.io>
> README Update

- build/tasks/publish-nylas-build-task.coffee
- docker/ubuntu32/Dockerfile
- script/cibuild-n1-ubuntu32
- script/dockerbuild
- script/mkrpm
In response to #254 and #139, I developed a Docker build for Linux that uses a 32-bit Docker image and builds N1. I used Atom's Fedora Docker buildfile as a template and went from there.
This PR adds the ability to use the Docker build, but needs complete testing for the `publish-nylas-build` task.
I was able to get the Docker to build the `deb` and `rpm` files like the regular CI build process does.
> [RFC] Linux 32-bit Docker build

- README.md
@mbilker recently renamed the repository and plugin to cypher, so I fixed the link to it in the README!
> Fix link to cypher

- internal_packages/ui-darkside/styles/darkside.less
like the phishing indicator in the darkside theme.
Before this change: http://pasteboard.co/2bUg8PU9.png
After: http://pasteboard.co/2bUj2Bmz.png
> (darkside) Fixed alignment of message headers

- src/components/scroll-region.cjsx
Scrollbars are currently always shown on hover, even if the content is fully fitted in the viewport, and has a non-native feel.
Fixing that requires correctly updating scrollbar state with content changes. For example, if the scrollbar is displayed (hovered) while page height is changed (e.g. a new message comes in), interacting with the scrollbar causes erratic behavior. This PR fixes that.
Fixes #1008.
> Fixes scrollbar display when content is not scrollable

- internal_packages/ui-darkside/README.md
- internal_packages/ui-darkside/styles/darkside.less
- static/images/ui-darkside/checkmark.svg
- static/images/ui-darkside/down-arrow.svg
- using recently added selectors for toolbars via 270d121
- inlined svgs in CSS to avoid path discrepancies between bundled and repo version of the theme
- fine-tuned design of message thread
- added top and bottom padding to message column to include more space below
- revised message list header toggle to match sidebar disclosure better
- changing `@close` color variable to `@danger` because versatility 
- added swipe-trash color change
> (darkside) using new toolbar selectors, svgs, etc

- ISSUE_TEMPLATE.md
There were several issues with the last issue template, here are some of them
- Instructions to user that should've been comments were not, they were shown as part of the issue
- Bullets were used instead of heading, the down side is that they weren't gonna be bullets only. Users were supposed to add paragraphs below them, thus breaking the styling.
- There were no separators in place
This PR addresses these issues
> Enhance issue template

- src/global/nylas-exports.coffee
In Cypher, I store the Keybase tokens in `config.cson` currently. With the recent integration of `atom-keytar`, I can store those authentication tokens into the system keychain where they are better protected than `config.cson` just like the account tokens.
> Add atom-keytar for use in extensions

- spec/stores/draft-store-spec.coffee
- src/browser/auto-update-manager.coffee
- src/browser/nylas-window.coffee
- src/config.coffee
- src/flux/nylas-api.coffee
- src/flux/stores/file-download-store.coffee
- src/nylas-env.coffee
- src/package-manager.coffee
- src/sheet-toolbar.cjsx
I was inspired by atom/atom#9627 to implement similar changes to N1. I did a simple grep to find cases of `dialog` used by the renderer and main processes and then converted them to the newer style. The specs were updated as well to account for these new changes.
> Use `remote` exports instead of `remote.require` for dialog

- src/global/nylas-exports.coffee
In Cypher, I use `ReactTestUtils` and was exposed as `React.addons.ReactTestUtils` in React 0.13, but no longer in React 0.14. To run spec tests properly, Cypher needs `ReactTestUtils` exposed.
This PR exposes it through `nylas-exports`, but it has the side-effect of exposing it while not in dev mode. If there is a better way to expose this during spec mode, please feel free to comment.
> Expose 'react-addons-test-utils' for spec testing external plugins

- internal_packages/composer-templates/spec/template-store-spec.es6
- internal_packages/preferences/lib/tabs/preferences-keymaps.jsx
- src/flux/stores/database-store.coffee
- static/index.js
Electron in 0.37.5 phases out the usage of `require('built-in-module')` in favor of `require('electron').builtInModule`. This commit corrects usage in some cases that cause N1 to not start under Electron 0.37.5.
> fix(imports): switch to Electron's require('electron')

- package.json
- src/components/evented-iframe.cjsx
- src/window-event-handler.coffee
When you hold down the meta key (⌘), and click on a link in a message,
the target application will not activate, so N1 will stay in the
foreground.
NB. The update of Electron is required to support (could be `0.36.8` as well), but I noticed that the upgrade was made previously, and reverted due to issues. (#847 #911)
Electron currently only supports this for OS X: https://github.com/atom/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options
Fixes #181
> Open links in background when ⌘ key is pressed

- spec/nylas-env-spec.coffee
This PR fixes the rather cryptic error during https://travis-ci.org/nylas/N1/jobs/122675741. I experienced a lot of these trying to work patch up N1 to work under Electron 0.37.
> `nylas-env-spec` handle remote method calls through `electron.remote`

- internal_packages/github-contact-card/lib/github-user-store.es6
Hopefully fixes #1991
I don't have N1 setup locally, so this is a blind shot–would appreciate somebody who has it set up to pull this and verify this fixes the issue, but as far as I can tell it should.
The gist is:
> Looking at the code, what you do is use the `search/users` endpoint to find users by email and taking the repos from there. You then load the repositories of the username, but we can't sort those by most-starred: "sort string Can be one of `created`, `updated`, `pushed`, `full_name`. Default: `full_name`" *([src](https://developer.github.com/v3/repos/#list-user-repositories))*
> What we could instead do is use the search API, which **allows us to search for repositories by a specific user and sort by most starred**. This is a tiny bit hacky, but works perfectly fine. E.g. …
> Fix Github Sidebar Plugin

- internal_packages/worker-sync/lib/nylas-long-connection.coffee
- src/flux/nylas-long-connection.es6
Ending the request sends it to the server (without an invalid GET data body).
Tested with 0.4.19 and 0.4.25.
> Doing write on a GET is invalid.

- src/config-schema.coffee
Using only "Menu Bar" confuses Linux users because ''Menu Bar'' word is only used withing Mac OS. So, also use "System Tray" word.
> Update title for system tray

- internal_packages/message-list/lib/message-participants.cjsx
- spec/models/contact-spec.coffee
- src/flux/models/contact.coffee
Office 365 likes to format email addresses as follows:
Last Name, First Name (Some Description) <email@address.org>
This causes Contact.firstName() (and hence sometimes displayName()) to return
"Last Name," which looks a bit odd in the message/thread views.
The intent of the commit is to correctly parse these names so that (using the
above example):
- firstName = "First Name"
- lastName = "Last Name (Some Description)"
- fullName = "First Name Last Name (Some Description)"
These behavioral changes only impact names containing a ','.
I don't know that this really provides exhaustive coverage of Office 365, and
keeping the description as part of the last name is not completely guilt free,
but it's not any worse than the previous state of affairs which also has
the description in the same …
> Parse Office 365 names

- build/resources/linux/nylas.desktop.in
- src/config-schema.coffee
Right now, N1 is showing under Programming Category. "Network" should be added to show under Internet Category.
> Show under Internet Category in Linux 

- internal_packages/message-list/lib/email-frame.jsx
- static/email-frame.less
This fixes issue #1128 
The horizontal scrollbar was not showing up in two cases for me:
1) A badly formatted email had some weird span with white-space: nowrap which caused the words to run off the screen
2) A wide image was only showing the left part.
Either case, the problem is the iframe not scrolling horizontally. I fiddled with the iframe for a while and couldn't get it to scroll, so I ended up setting overflow on the body of the iframe page instead.
**Before:**
**After (notice border to the right):**
> horizontal scrollbar does not appear when viewing wide email

- build/resources/linux/redhat/nylas.spec.in
- src/flux/models/utils.coffee
Hi,
I was found the problem in Linux, the browser cannot detect timezone by function Inlt so I used moment.tz.guess() function to get timezone.
> fixed bug timezone cannot detect in fedora

- _includes/top.html
Removed unneeded twitter:app meta data - those are only needed for sites which have native apps available on Google Play and iOS App Store.
> Removed unneeded twitter:app meta data

- internal_packages/phishing-detection/lib/main.jsx
For example, the following is *not* suspicious:
```
From: foo@example.org
Reply-To: bar@example.org
```
While the following remains suspicious:
```
From: foo@example.org
Reply-To: foo@example.com
``` 
This commit fixes #2342.
> warns suspicious message only on differing domain

- script/clean
The clean script fails since productName is "Nylas N1" which contains a space and it appears to pkill 2 patterns. This is causing the script to stop in my linux machine. Now the productName is wrapped with quotes to prevent this from happening.
> Fix failing clean script

- src/browser/application.es6
When running against a custom Sync Engine, viewing the onboarding page
on startup does not make much sense. This here adds code that checks for
the `env` of the Nylas config and skips the onboarding if it is `local`
or `custom`.
This fixes #2468.
> Make display of onboarding page conditional.

- internal_packages/phishing-detection/lib/main.jsx
- internal_packages/phishing-detection/package.json
This commit improves on nylas/N1#2343 (which allowed From and
Reply-To to be different aliases @ the same domain) by allowing the
address to differ by a subdomain.
For example, the pairs:
From:     foo@bar.com
Reply-To: foo@sub.bar.com
From:     foo@bar.co.uk
Reply-To: foo@other.bar.co.uk
From:     foo@bar.com
Reply-To: foobar@bar.com
are each now allowed without warning.
> Don't show phishing warning if Reply-To and From are on the same domain; even with differing subdomain

- internal_packages/unread-notifications/lib/main.es6
- internal_packages/unread-notifications/spec/main-spec.es6
Relatively minor, but I noticed it while poking around in the file, and
it started to bother me.
Consider the case where a user launches N1, and has 3 unreads since
their last launch. Additionally, after N1 has launched, they begin
receiving a new mail every 2 seconds.
Current behavior would be a notification for 1 of the 3 unread emails,
then every 2 seconds a notification for the most recently received mail.
They would only finally receive notifications for the other 2 original
messages once they stopped getting new mail.
> Change pending unread notification stack to be a queue

- internal_packages/worker-sync/lib/nylas-long-connection.coffee
When APIRoot is using https, the port will forced to be 443 even when APIRoot
indicates another port. This is because of the line options.port = 443
overwriting the correct options.port extracted by url.parse. This is fixed by
removing the problematic line. The default port is still 443 if you look into
https.js. In case we want a different default port in the future, we can do
options.port = options.port || 443.
> Fix incorrect port number when using https

- src/components/tokenizing-text-field.cjsx
This modifies the behavious when pasting into the to, cc or bcc fields of a new draft. This allows you to, for example, copy the domain of the email address from the clipboard and type the addressee and then paste the domain. Any text already in the input field is not automatically deleted. Rather the pasted
text is added to the already existing text. If the new contents of the email field now matches as an email address (based on RegExpUtils.emailRegex().test()), then the address is immediately tokenized. If the new input text doesn't match as an email, just append the new text and wait for further input.
> Pasting into a participant field now preserves any text already there (Issue #2410)

- build/resources/linux/debian/postinst
Allows the deb package to be installed on Linux Mint 18. Xenial is not yet supported in nylas repos. Anyway, the postscript still works, creating the nylas.list files with the "vivid" version. I know Xenial is LTS (as Linux Mint 18 Sarah).
> Linux Mint 18 support.

- spec/stores/draft-helpers-spec.es6
A previous commit (ad04775) added an fdescribe() to one of the tests in
draft-helpers-spec. This changes that to a regular describe() so that
all tests will be run when running ./N1 --test.
> Small fix to re-enable tests when running ./N1 --test

- src/flux/models/contact.coffee
added exclusions for Dr., Mrs., Mr., Mx., Prof., and Ph.D. in the `firstName` method of `contact.coffee` so that their first name would not show up in emails as such
> improve first name parser by adding honorific exclusions

- src/apm-wrapper.coffee
Adds the `--production` flag to `apm install`. It should both be faster and allows people to install great plugins like, `n1-unsubscribe`!
*Currently, users have to install our plugin, reload Nylas, then go back to the plugin page to reactivate the plugin. The error is entirely due to all of the dev-dependencies currently installed by `apm install`, which shouldn't be downloaded anyway. See #2723 for how to reproduce the install problem*
I built and tested the fork locally:
> Closes #2723 -> apm ignore plugin dev-dependencies

- spec/nylas-protocol-handler-spec.coffee
- spec/nylas-protocol-handler-spec.es6
for #2884 
I cherry picked the shortest spec to figure out a process for doing these conversions, which I'll document for others on the original issue.
> convert nylas-protocol-handler-spec to ES6

- src/flux/models/utils.coffee
Because I think a single execution should be faster than 2 separate.
> use single regex exec for toEquivalentEmailForm

- internal_packages/ui-darkside/styles/darkside-composer.less
- internal_packages/ui-darkside/styles/darkside-message-list.less
- Removed styles for composer fields that were no longer useful
- reduced padding around 'attachment' icon in collapsed thread container
- updating attachment selector names for custom attachment hover styles
> (darkside) fixing composer fields spacing

- internal_packages/onboarding/lib/account-types.es6
Google renamed Google Apps (both 'normal' and education editions) to G Suite on 2016-09-29 ([announcement](https://blog.google/products/g-suite/all-together-now-introducing-g-suite/)). Updated text for account selection to match Google's branding.
> Rename Google Apps to G Suite in onboarding

- docs/Architecture.md
Pretty minor change! It looks like the location of the Flux architecture diagrams got moved around on the Flux docs since the last changes on Architecture.md; this change updates the link here to the new/current location of the diagram.
> Fix link to Flux diagram in docs/Architecture.md

- README.md
I've changed sentences that refer to N1 to refer ro Nylas Mail.
I'm unclear why and how there is no leading paragraph describing this renaming decision and preventing confusion. I would imagine part of re-branding would be to inform existing users of the re-brand (?) and that these things would be thought of before rolling out the re-brand.
> Update README.md to fix inconsistent references of N1

- README.md
Seems like the website structure is changed entirely causing the url for the image in README.md to be broken.
> Fix broken image url in README.md
