nylas/nylas-mail

examples/N1-Filters/lib/main.coffee

Spotted this in the docs :grin:

Fix little typo

---

build/README.md

Addresses issue https://github.com/nylas/N1/issues/29

Adding node version information to build/README.md

---

CONTRIBUTING.md

Looks like a small typo slipped through :)

fix(docs): correct SMPT->SMTP

---

script/clean

I discovered in the clean script that there are some remnants of the Atom editor project. I refactored the names to their current directory names.

Change atom to nylas in clean script

---

src/regexp-utils.coffee

fixes https://github.com/nylas/N1/issues/111

fix email validation

---

internal_packages/preferences/stylesheets/preferences.less
internal_packages/ui-dark/styles/ui-variables.less
static/dropdowns.less
static/index.less
static/variables/ui-variables.less

Default select tag looks creepy, so here are some changes that make dropdowns look way better.

Setup stylesheets for dropdown (select) control

---

internal_packages/account-sidebar/package.json
internal_packages/attachments/package.json
internal_packages/category-picker/package.json
internal_packages/composer-signature/package.json
internal_packages/composer-spellcheck/package.json
internal_packages/composer/package.json
internal_packages/events/package.json
internal_packages/inbox-contact-elements/package.json
internal_packages/message-list/package.json
internal_packages/mode-switch/package.json
internal_packages/notification-mailto/package.json
internal_packages/notification-update-available/package.json
internal_packages/notifications/package.json
internal_packages/onboarding/package.json
internal_packages/plugins/package.json
internal_packages/preferences/package.json
internal_packages/search-bar/package.json
internal_packages/sidebar-fullcontact/package.json
internal_packages/thread-list/package.json
internal_packages/tooltip/package.json
internal_packages/ui-dark/package.json
internal_packages/ui-light/package.json
internal_packages/undo-redo/package.json
internal_packages/unread-notifications/package.json
internal_packages/worker-sync/package.json
internal_packages/worker-ui/package.json

Changed from 'Propietary' to 'GPLv3' to match `LICENSE.md`

Internal package.json license: GPLv3

---

docs/GettingStarted.html

In:
https://nylas.com/N1/docs/GettingStarted.html#installing-a-dependency
**from**
**to**

remove line break

---

_sass/_nav.scss

Fix navbar in Safari

---

README.md

Perhaps to increase developer awareness. 🤗

Added link to plugin and theme repo

---

internal_packages/message-list/lib/thread-archive-button.cjsx
internal_packages/message-list/lib/thread-toggle-unread-button.cjsx

I was just starring a the code.

Harmonize require and remove unused ones.

---

keymaps/templates/Google Inbox.cson

Added keyboard shortcuts for Google Inbox (different from Gmail).

Inbox shortcuts

---

build/tasks/publish-nylas-build-task.coffee

We weren't setting the correct Content-Type when uploading files to S3, which made S3 serve them with `application/octet-stream` (bad!). This diff fixes this.

set the ContentType when uploading packages to S3.

---

src/browser/nylas-window.coffee
static/index.html

Changes to be committed:
modified:   static/index.html

Change the title bar to say Nylas N1 instead of Nylas

---

keymaps/templates/Apple Mail.cson

Fixes https://github.com/nylas/N1/issues/1301

More closely match Apple mail shortcuts

---

README.md

Can be seen here: http://jamiewilson.io/darkside/ and here: https://github.com/jamiewilson/darkside

Adding Darkside theme

---

README.md

Updated readme.md with Less is More minimal N1 theme.

Less is More Theme

---

README.md

just adding a theme to the list :hatching_chick:

add toogabooga theme to readme

---

keymaps/templates/Apple Mail.cson

Added jumping, search focus, select, star and archive keybinds to Apple
Mail keymap

Add Mail.app keybinds

---

internal_packages/phishing-detection/lib/main.jsx
internal_packages/phishing-detection/stylesheets/phishing.less

Before: http://pasteboard.co/2c06q5IH.png
After: http://pasteboard.co/2c081AqZ.png

Fixed text overflow in phishing detection indicator

---

src/browser/auto-update-manager.coffee

I forgot that the `AutoUpdateManager` is run from the main process

Fix my mistake with AutoUpdateManager

---

internal_packages/ui-darkside/styles/darkside.less

(darkside) correcting window buttons, adding input focus

---

internal_packages/preferences/lib/tabs/workspace-section.jsx
src/system-start-service.es6

For more information see issue #1251.

Linux launch on start

---

README.md

Added in README a new community plugin that ["Website Launcher"](https://github.com/adriangrantdotorg/nylas-n1-background-webpage)

README - Added new community plugin, Website Launcher 

---

CONTRIBUTING.md
README.md
build/tasks/docs-render-task.coffee
docs/README.md
examples/README.md
internal_packages/message-list/spec/autolinker-fixtures/readme-in.html
internal_packages/message-list/spec/autolinker-fixtures/readme-out.html
internal_packages/plugins/lib/tab-installed.jsx
src/flux/models/account.es6
src/flux/models/calendar.coffee
src/flux/models/contact.coffee
src/flux/models/file.coffee
src/flux/models/message.es6
src/flux/models/thread.es6
src/flux/tasks/task.es6
src/window-event-handler.coffee

Also updated schemes of some links to https for consistency

Update broken links for guides, docs, and API

---

docs/Overview.md

All the links presents [here](https://github.com/nylas/N1/blob/master/docs/Overview.md) are broken. I have updated all the links.

Fixed broken links.

---

internal_packages/keybase/README.md
internal_packages/keybase/lib/decrypt-button.cjsx
internal_packages/keybase/lib/decryption-preprocess.coffee
internal_packages/keybase/lib/key-adder.cjsx
internal_packages/keybase/lib/key-manager.cjsx
internal_packages/keybase/lib/modal-key-recommender.cjsx
internal_packages/keybase/lib/passphrase-popover.cjsx
internal_packages/keybase/lib/pgp-key-store.cjsx
internal_packages/keybase/lib/private-key-popover.cjsx
internal_packages/keybase/stylesheets/main.less

This update to the PGP plugin overhauls the Decrypt UI, adds a bunch of error messaging, and corrects some bugs in the encryption key picker modal.

pgp-plugin update

---

README.md

This theme hides the account list sidebar.

Update README to include Kleinstein theme

---

src/browser/nylas-window.coffee

Enables showing/hiding of the menubar as per feature request #1181

Enables showing/hiding of menubar

---

README.md

Hi, 
I created two simple gradient based themes. Would love to get included in the readme! 
Thanks :)

Updated readme to include BoraBora and Honeyduke theme

---

README.md

A simple light theme with a hiding sidebar.

Add Snow to README

---

README.md

Darkish is an easy-for-eyes and experimental theme for Nylas N1

Add link for Darkish theme

---

README.md

Fixing broken screenshot link

---

internal_packages/composer-emoji/package.json

Match JSON style to rest of file

Fix JSON spacing

---

src/browser/main.js

Per: https://github.com/nylas/N1/commit/f8f0cb206f53183698ee1648a7a789bfbf2598ac

Fix this line on non-POSIX systems, such as Windows

---

CHANGELOG.md

http://grammar.yourdictionary.com/spelling-and-word-lists/misspelled.html

Typo: mispelled > misspelled

---

internal_packages/composer-signature/styles/composer-signature.less
internal_packages/preferences/stylesheets/preferences-accounts.less
internal_packages/preferences/stylesheets/preferences-mail-rules.less

Normalized size of buttons in preferences (fixes #2753)

---

README.md

Add the GitHub community plugin
